#export LANG=en_US.utf8
#export LC_ALL=en_US.utf8

export PY_USER_BIN=$(python -c 'import site; print(site.USER_BASE + "/bin")')
export PATH=${HOME}/.bin:$PY_USER_BIN:$PATH

#export NNTPSERVER="news.udc.es"
#export NNTPSERVER="talia.mad.ttd.net"
#export NNTPSERVER="news.readfreenews.net"
#export NNTPSERVER="news-8.escomposlinux.org"
#export NNTPSERVER="ficbbs.org:9999"
#export NNTPSERVER="localhost"
#export NNTPSERVER="news-13.escomposlinux.org"

#FiCBBS stuff
#FIDO="/home/emilioj/.ficbbs"
#GOLDED="/home/emilioj/.ficbbs/golded"
#FIDOCONFIG="/home/emilioj/.ficbbs/config"
#export FIDO FIDOCONFIG GOLDED
#alias ficbbs='/usr/sbin/binkd -p -P 2:348/105 $FIDO/binkd.cfg'

